### ISSUE TITLE
深入Dubbo - 聊聊代码 | 吴小胖

### ISSUE THREAD

**Issue by xxxlxy2008** [xxxlxy2008/blogtalk#1]
https://xxxlxy2008.github.io/2020/04/02/1-Dubbo-%E6%BA%90%E7%A0%81%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/ 

 聊聊代码，谈谈架构

**Comment by xxxlxy2008** [comment]
来来来，一起读源码吧~

**Comment by lysu** [comment]
写的太深了，完全看不懂啊。。。
